--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/VBasket
build-by-default: true
branches:
- main
projects:
  VBasket:
    path: ""
    libs:
      - src: VennDev/LibVapmPMMP/LibVapmPMMP
        version: ^1.8
        branch: "main"
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6
        branch: "pm5"
...
