name: VBasket
api: 5.0.0
author: VennVDev
main: vennv\vbasket\VBasket
version: 1.0.2

commands:
  vbasket:
    description: VBasket command
    usage: /vbasket give <player> <type> <amount>
    aliases: [vbkt]
    permission: vbasket.command
    permission-message: You don't have permission to use this command.

permissions:
  vbasket.command:
    description: vbasket command permission
    default: op
